Vagrant.configure("2") do |config|
  # 设置基础 box
  config.vm.box = "generic/ubuntu2204"
  config.vm.synced_folder "./data", "/vagrant_data"
  config.vm.hostname = "ubuntu22"

  # 配置虚拟机的 CPU 和内存
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 2
  end

  # 配置桥接网络和静态 IP（不指定网络接口名称）
  config.vm.network "public_network", ip: "192.168.1.115"
end
